# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cran: https://cran.rstudio.com
sudo: false

branches:
  only:
  - master

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'

env:
  - NETLIFY_SITE_ID=2f326b36-6ea6-465e-ab15-66ebdd84a3ec
  # NETLIFY_AUTH_TOKEN set in travis settings